"""LLM p2 on the transformed sets (CPU only): metrics per set x model, drop vs identity, Addendum C survival rule, matched-pair flips.
Writes results/adv/LLM_TRANSFORMS.md/json. Only complete (set, model) pairs are analysed; incomplete ones are listed as such."""
from __future__ import annotations
import json, os
import numpy as np
from ..systems import common as C
from .common import ADV, ADV_DATA, evaluate, load_split, summary_with_ci
from .run_llm import MODELS, RAWDIR, SETS, SYSTEM

KEY = ("delta_exact_match", "preservation_accuracy", "revision_recall")


def load_preds(s, model, tasks):
    path = os.path.join(RAWDIR, s, model.replace(":", "_"), f"{SYSTEM}.jsonl")
    if not os.path.exists(path):
        return {}
    T = {t["item_id"]: t for t in tasks}
    out = {}
    for l in open(path):
        r = json.loads(l)
        out[r["item_id"]] = C.parse_delta(SYSTEM, r["content"], T[r["item_id"]])[0]
    return out


def main():
    R, notes = {}, []
    for s in SETS:
        tasks, golds = load_split("test_id", os.path.join(ADV_DATA, s))
        for m in MODELS:
            preds = load_preds(s, m, tasks)
            if len(preds) < len(tasks):
                notes.append(f"{s} / {m}: {len(preds)}/{len(tasks)} items (excluded)")
                continue
            ev = evaluate(preds, tasks, golds)
            R[f"{s}|{m}"] = summary_with_ci(ev, b=1000) | {"_label_ok": ev["label_ok"]}
    # matched pairs: base item (identity set) and its variant must both be label-exact
    pairs = json.load(open(os.path.join(ADV_DATA, "matched_pairs", "pairs.json")))
    flips = {}
    for m in MODELS:
        a, b = R.get(f"identity|{m}"), R.get(f"matched_pairs|{m}")
        if a and b:
            ok = [a["_label_ok"][p["base"]] and b["_label_ok"][p["variant"]] for p in pairs]
            flips[m] = {"pairs": len(pairs), "both_correct": float(np.mean(ok)),
                        "base_correct": float(np.mean([a["_label_ok"][p["base"]] for p in pairs])),
                        "variant_correct": float(np.mean([b["_label_ok"][p["variant"]] for p in pairs]))}
    for v in R.values():
        v.pop("_label_ok", None)
    # Addendum C: survives = preservation CI upper < 0.97 OR recall CI upper < 0.85, AND delta-EM < 0.9, on EVERY set
    surv = {}
    for m in MODELS:
        rows = {s: R[f"{s}|{m}"] for s in SETS if f"{s}|{m}" in R and s != "matched_pairs"}
        if len(rows) < len(SETS) - 1:
            surv[m] = "incomplete"
            continue
        ok = all((r["preservation_accuracy"][2] < 0.97 or (r["revision_recall"][2] < 0.85 if r["revision_recall"][2] == r["revision_recall"][2] else False)) and r["delta_exact_match"][0] < 0.9 for r in rows.values())
        surv[m] = bool(ok)
    json.dump({"results": R, "matched_pair_flips": flips, "survives_addendum_C": surv, "notes": notes}, open(os.path.join(ADV, "LLM_TRANSFORMS.json"), "w"), indent=1)
    f = lambda x: f"{x[0]:.3f} [{x[1]:.3f}, {x[2]:.3f}]"
    L = ["# LLM p2 on transformed sets (generated by adv/analyze_llm_transforms.py)", "",
         "| set | model | delta-EM | preservation | revision recall | label-exact | claim macro-F1 |", "|---|---|---|---|---|---|---|"]
    for s in SETS:
        for m in MODELS:
            r = R.get(f"{s}|{m}")
            if r:
                L.append(f"| {s} | {m} | {f(r['delta_exact_match'])} | {f(r['preservation_accuracy'])} | {f(r['revision_recall'])} | {r['label_em']:.3f} | {r['claim_macro_f1']:.3f} |")
    L += ["", "## Drop vs identity re-realisation (delta-EM, point estimates)", "", "| set | " + " | ".join(MODELS) + " |", "|---|" + "---|" * len(MODELS)]
    for s in SETS:
        L.append(f"| {s} | " + " | ".join((f"{R[f'{s}|{m}']['delta_exact_match'][0] - R[f'identity|{m}']['delta_exact_match'][0]:+.3f}" if f"{s}|{m}" in R and f"identity|{m}" in R else "n/a") for m in MODELS) + " |")
    L += ["", f"## Matched pairs (resolving base item + one-edit variant; {len(pairs)} pairs)", "", json.dumps(flips, indent=1), "",
          f"## Addendum C survival rule (per model, every non-pair set): {json.dumps(surv)}", "", "Notes: " + "; ".join(notes) if notes else "No incomplete runs."]
    open(os.path.join(ADV, "LLM_TRANSFORMS.md"), "w").write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
