"""Extra cheap attackers + decomposition of the text-only attacker. Writes research/results/ATTACKERS.md.

Question: can a cheap classifier solve the benchmark without understanding narrative state?
Targets: (a) evidence category from evidence text; (b) per-claim changed-vs-KEEP; (c) per-item delta exactness is NOT attackable
(it needs 10 labels) so we report the best per-claim attacker's implied item-EM by predicting all 10 claims.
"""
from __future__ import annotations
import os
import numpy as np
from scipy.sparse import csr_matrix, hstack
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, confusion_matrix
from .io import TEST_SPLITS, load_gold, load_task
from .leakage import cat_of, claim_rows, delex, meta_feats

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")


def text_attackers():
    Ttr, Gtr = load_task("train"), load_gold("train")
    ytr = [cat_of(g) for g in Gtr]
    ev = lambda T, d: [delex(t["evidence"]) if d else t["evidence"] for t in T]
    variants = {
        "bow(delex)": (lambda: CountVectorizer(ngram_range=(1, 2), min_df=2), True),
        "bow(raw words incl. names)": (lambda: CountVectorizer(ngram_range=(1, 2), min_df=2), False),
        "tfidf word 1-3gram(delex)": (lambda: TfidfVectorizer(ngram_range=(1, 3), min_df=2), True),
        "char 2-5gram(delex)": (lambda: TfidfVectorizer(analyzer="char_wb", ngram_range=(2, 5), min_df=3), True),
        "length+punct+slot only": (None, True),
    }
    rows = {}
    for name, (mk, d) in variants.items():
        for sp in TEST_SPLITS:
            Te, Ge = load_task(sp), load_gold(sp)
            yte = [cat_of(g) for g in Ge]
            if mk is None:
                Xtr = np.array([meta_feats(t) for t in Ttr], float); Xte = np.array([meta_feats(t) for t in Te], float)
                m = RandomForestClassifier(300, random_state=0).fit(Xtr, ytr)
            else:
                v = mk(); Xtr = v.fit_transform(ev(Ttr, d)); Xte = v.transform(ev(Te, d))
                m = LogisticRegression(max_iter=3000).fit(Xtr, ytr)
            rows[(name, sp)] = f1_score(yte, m.predict(Xte), average="macro")
    return variants, rows


def decompose():
    """Per evidence family: how well does the text-only attacker do, and what is the Bayes-optimal family-only rule?"""
    Ttr, Gtr = load_task("train"), load_gold("train")
    Te, Ge = load_task("test_id"), load_gold("test_id")
    v = CountVectorizer(ngram_range=(1, 2), min_df=2)
    m = LogisticRegression(max_iter=3000).fit(v.fit_transform([delex(t["evidence"]) for t in Ttr]), [cat_of(g) for g in Gtr])
    pred = m.predict(v.transform([delex(t["evidence"]) for t in Te]))
    fam = [g["meta"]["evidence_kind"] for g in Ge]
    y = [cat_of(g) for g in Ge]
    out = {}
    for f in sorted(set(fam)):
        ix = [i for i, x in enumerate(fam) if x == f]
        out[f] = (len(ix), float(np.mean([pred[i] == y[i] for i in ix])), {c: sum(y[i] == c for i in ix) for c in ("resolving", "irrelevant", "contradictory")})
    # Bayes-optimal family-only rule estimated on TRAIN, evaluated on test_id: shows how much is "family semantics" vs wording
    famtr = [g["meta"]["evidence_kind"] for g in Gtr]; ytr = [cat_of(g) for g in Gtr]
    table = {}
    for f, c in zip(famtr, ytr):
        table.setdefault(f, {}).setdefault(c, 0); table[f][c] += 1
    rule = {f: max(d, key=d.get) for f, d in table.items()}
    fam_only = [rule.get(f, "irrelevant") for f in fam]
    return out, f1_score(y, fam_only, average="macro"), f1_score(y, pred, average="macro"), confusion_matrix(y, pred, labels=["resolving", "irrelevant", "contradictory"])


def main():
    variants, rows = text_attackers()
    L = ["# Cheap-attacker report (generated by research/ssr_bench/attackers.py)", "",
         "Macro-F1 for predicting the evidence category from evidence text/metadata only (chance 0.333). Trained on `train`, tested per split. Pre-registered gate G1 limit 0.60 (word 1-2gram LR / RF), G2 limit 0.40 (metadata).", "",
         "| attacker | " + " | ".join(TEST_SPLITS) + " |", "|---|" + "---|" * len(TEST_SPLITS)]
    for name in variants:
        L.append(f"| {name} | " + " | ".join(f"{rows[(name, sp)]:.3f}" for sp in TEST_SPLITS) + " |")
    out, fam_f1, lr_f1, cm = decompose()
    L += ["", "## Decomposition of the text-only attacker on test_id", "",
          f"- word-1/2gram LR macro-F1 = {lr_f1:.3f}; an attacker that only knows the *evidence family* (event kind / assertion / noop) and picks the train-majority category = {fam_f1:.3f}.",
          "- So the share of attacker skill that is explained by evidence *family* (a semantic property: e.g. noop sentences are irrelevant by meaning, give/drop/pickup are mostly contradictory-or-resolving) is the part that cannot be removed without deleting that evidence type.", "",
          "| evidence family | n (test_id) | attacker accuracy within family | true category counts |", "|---|---|---|---|"]
    for f, (n, acc, cnt) in out.items():
        L.append(f"| {f} | {n} | {acc:.3f} | {cnt} |")
    L += ["", f"Confusion matrix (rows = true resolving/irrelevant/contradictory; cols = predicted): `{cm.tolist()}`", ""]
    # per-claim attackers
    Xtr, ytr, txt = claim_rows("train")
    L += ["## Per-claim 'changed vs KEEP' attackers (positive-class F1; gate G3 limit 0.70)", "", "| attacker | " + " | ".join(TEST_SPLITS) + " |", "|---|" + "---|" * len(TEST_SPLITS)]
    vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(2, 5), min_df=3)
    Str = hstack([csr_matrix(Xtr), vec.fit_transform(txt)]).tocsr()
    lr = LogisticRegression(max_iter=5000, class_weight="balanced").fit(Str, ytr)
    rf = RandomForestClassifier(300, random_state=0, class_weight="balanced").fit(Xtr, ytr)
    r1, r2 = [], []
    for sp in TEST_SPLITS:
        X, y, tx = claim_rows(sp)
        r1.append(f1_score(y, lr.predict(hstack([csr_matrix(X), vec.transform(tx)]).tocsr())))
        r2.append(f1_score(y, rf.predict(X)))
    L.append("| LR on claim features + evidence char n-grams | " + " | ".join(f"{x:.3f}" for x in r1) + " |")
    L.append("| RF on claim features only (slot offset, mention, attr, position) | " + " | ".join(f"{x:.3f}" for x in r2) + " |")
    L += ["", "An attacker that reaches the symbolic parser's level (item delta-EM ~1.0, claim-F1 ~1.0) would compromise the benchmark; none of the above comes close."]
    open(os.path.join(OUT, "ATTACKERS.md"), "w").write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
