"""Deep analysis (post-hoc / exploratory EXCEPT the pre-registered criterion in analyze.py). Writes DEEP_ANALYSIS.md/json.

Sections: A four-way final-answer-vs-delta table; B per-intervention metrics; C failure structure (grouped + clustered logistic);
D OOD vs ID; E model comparison (McNemar, paired). Everything is computed from raw predictions via evaluate.llm_predictions.
"""
from __future__ import annotations
import json, os
from collections import Counter, defaultdict
import numpy as np
from scipy.stats import binomtest
from sklearn.linear_model import LogisticRegression
from . import stats
from .evaluate import llm_predictions
from .io import TEST_SPLITS, load_gold, load_task
from .generate import SPLITS
from .systems import common as C

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")
MODELS = ["qwen2.5:7b", "llama3:latest", "qwen3:8b", "mistral:7b"]
DELTA = ["p1_zero_shot_delta", "p2_explicit_revision", "p3_regenerate", "p4_self_consistency"]
NB = int(os.environ.get("SSR_BOOT", 2000))
RNG = np.random.default_rng(0)


def build_rows(model, system):
    rows = []
    for sp in TEST_SPLITS:
        tasks = {t["item_id"]: t for t in load_task(sp)}
        gold = {g["item_id"]: g for g in load_gold(sp)}
        preds, _ = llm_predictions(model, system, sp, tasks)
        _, ans = llm_predictions(model, "p5_direct_qa", sp, tasks)
        for iid, p in preds.items():
            t, g = tasks[iid], gold[iid]
            ne = coll = ncoll = anyrev = anyconf = missed = confok = 0
            for c in t["claims"]:
                gl, gv = g["labels"][c["id"]]["label"], C.norm(g["labels"][c["id"]]["value"])
                pl, pv = p[c["id"]]
                ex = gl == pl and (gl != "REVISE" or gv == pv)
                ne += ex
                if gl == "KEEP" and pl in ("REVISE", "CONFLICT"):
                    coll, ncoll = 1, ncoll + 1
                anyrev |= pl == "REVISE"; anyconf |= pl == "CONFLICT"
                if gl == "REVISE" and not ex:
                    missed = 1
                if gl == "CONFLICT" and ex:
                    confok = 1
            pid = t["probe"]["claim_id"]
            pc = next(c for c in t["claims"] if c["id"] == pid)
            pl, pv = p[pid]
            qa_delta = (C.norm(pc["value"]) if pl in ("KEEP", "CONFLICT") else pv) == C.norm(g["probe_answer"])
            w, m = g["world"], g["meta"]
            rows.append(dict(
                split=sp, story=g["story_id"], item=iid, cat=m["category"], kind=m["evidence_kind"].split(":")[0] if m["evidence_kind"] != "noop" else "noop",
                family=m["evidence_kind"], bounded=m["scope_bounded"], dependent=m["has_dependent_change"], n_changed=m["n_changed"],
                exact=int(ne == len(t["claims"])), n_exact=ne, collateral=coll, n_collateral=ncoll, any_rev=int(anyrev), any_conf=int(anyconf),
                missed=missed, conf_ok=confok, qa_delta=int(qa_delta), qa_direct=int(ans.get(iid) == C.norm(g["probe_answer"])) if iid in ans else None,
                # features
                n_events=len(w["events"]), n_noops=sum(e["kind"] == "noop" for e in w["events"]), n_chars=len(w["chars"]), n_props=len(w["props"]),
                n_sent=m["n_story_sentences"], ev_slot=m["evidence_slot"], ev_dist=m["evidence_slot"] - max(e["slot"] for e in w["events"]),
                n_after=sum(e["slot"] > m["evidence_slot"] for e in w["events"]), shuffled=int(m["narration"] == "shuffled"),
                heldout=int(m["template_heldout"]), near=int(SPLITS[sp]["pools"] == "NEAR"), past=int(m["slot_rel"] == "past"),
                resolving=int(m["category"] == "resolving"), contradictory=int(m["category"] == "contradictory")))
    return rows


def prop_ci(rows, f, key="story", b=NB):
    st = defaultdict(list)
    for r in rows:
        st[r[key]].append(r)
    ids = list(st)
    if not ids:
        return None, None, None, 0
    vals = np.array([[sum(f(r) for r in st[i]), len(st[i])] for i in ids], dtype=float)
    est = vals[:, 0].sum() / vals[:, 1].sum()
    idx = RNG.integers(0, len(ids), size=(b, len(ids)))
    bs = vals[idx].sum(1)
    bs = bs[:, 0] / bs[:, 1]
    return est, *np.percentile(bs, [2.5, 97.5]), len(rows)


def fmt(t):
    return "n/a" if t[0] is None else f"{t[0]:.3f} [{t[1]:.3f}, {t[2]:.3f}] (n={t[3]})"


def four_way(rows, answer_key):
    c = Counter()
    for r in rows:
        a = bool(r[answer_key]) if r[answer_key] is not None else None
        if a is None:
            continue
        d = "exact" if r["exact"] else ("substantial" if (r["n_exact"] >= 8 and not r["collateral"]) else "wrong")
        c[(a, d)] += 1
    return c


def main():
    R = {m: {s: build_rows(m, s) for s in DELTA} for m in MODELS}
    R = {m: {s: v for s, v in d.items() if v} for m, d in R.items()}
    L = ["# Deep analysis (generated by research/ssr_bench/deep_analysis.py)", "",
         "All intervals are 95% story-clustered bootstrap CIs. Sections B-E are exploratory/descriptive; only analyze.py section 8 applies the pre-registered criterion.", ""]
    J = {}

    # ---------------- A four-way
    L += ["## A. Final answer vs state delta", "",
          "Final answer = the probed claim's value (gold: value after the evidence; for contradictory items the unchanged value). Two sources: (i) `QA-from-delta` = what the model's own delta implies, (ii) `direct QA` = separate single-answer prompt (p5, no ledger).",
          "Delta: *exact* = all 10 claims exact; *substantial* = not exact but >=8/10 exact and no collateral revision; *wrong* = otherwise.", ""]
    for src, key in (("QA-from-delta", "qa_delta"), ("direct QA (p5)", "qa_direct")):
        L += [f"### Final answer source: {src}", "", "| model | system | scope | answer | delta | count | % of scope |", "|---|---|---|---|---|---|---|"]
        for m, d in R.items():
            for s, rows in d.items():
                for scope, sel in (("test_id", [r for r in rows if r["split"] == "test_id"]), ("all splits", rows)):
                    cnt = four_way(sel, key)
                    tot = sum(cnt.values())
                    for (a, dl), n in sorted(cnt.items(), key=lambda kv: (not kv[0][0], kv[0][1])):
                        L.append(f"| {m} | {s} | {scope} | {'correct' if a else 'incorrect'} | {dl} | {n} | {100 * n / tot:.1f}% |")
                    J.setdefault("four_way", {}).setdefault(src, {}).setdefault(m, {}).setdefault(s, {})[scope] = {f"{a}|{dl}": n for (a, dl), n in cnt.items()}
        L.append("")
    L += ["### Does answer accuracy hide delta errors? P(delta not exact | answer correct), by category / temporal view / split", "",
          "| model | system | answer source | group | P(delta not exact \\| answer correct) | P(collateral \\| answer correct) |", "|---|---|---|---|---|---|"]
    for m, d in R.items():
        for s, rows in d.items():
            for src, key in (("QA-from-delta", "qa_delta"), ("direct QA", "qa_direct")):
                groups = [("all", rows)] + [(f"cat={c}", [r for r in rows if r["cat"] == c]) for c in ("resolving", "irrelevant", "contradictory")] + \
                         [("resolving, bounded", [r for r in rows if r["cat"] == "resolving" and r["bounded"]]), ("resolving, unbounded", [r for r in rows if r["cat"] == "resolving" and not r["bounded"]])] + \
                         [(f"split={sp}", [r for r in rows if r["split"] == sp]) for sp in TEST_SPLITS]
                for gname, sel in groups:
                    sel = [r for r in sel if r[key]]
                    if len(sel) >= 15:
                        L.append(f"| {m} | {s} | {src} | {gname} | {fmt(prop_ci(sel, lambda r: 1 - r['exact']))} | {fmt(prop_ci(sel, lambda r: r['collateral']))} |")

    # ---------------- B per-intervention
    L += ["", "## B. Paired-intervention metrics (per evidence type; unit = story)", "",
          "Definitions (fixed here, before inspection): sensitivity = share of resolving items with every gold REVISE claim exactly revised; precision = value-aware (analyze.py); distractor invariance = share of irrelevant items with no claim changed; contradiction response = share of contradictory items with the CONFLICT claim exactly flagged (and `overwrite rate` = share with any REVISE); flip accuracy = share of matched triples where resolving item has >=1 REVISE, irrelevant item has none, contradictory item has a CONFLICT and no REVISE (label-level).", "",
          "| model | system | scope | revision sensitivity | distractor invariance | contradiction response | contradiction overwrite rate | flip accuracy (triples) |", "|---|---|---|---|---|---|---|---|"]
    for m, d in R.items():
        for s, rows in d.items():
            for scope, sel in (("test_id", [r for r in rows if r["split"] == "test_id"]), ("all splits", rows)):
                res_ = [r for r in sel if r["cat"] == "resolving"]; irr = [r for r in sel if r["cat"] == "irrelevant"]; con = [r for r in sel if r["cat"] == "contradictory"]
                tr = defaultdict(dict)
                for r in sel:
                    tr[r["story"]][r["cat"]] = r
                triples = [{"story": k, **{c: v for c, v in x.items()}} for k, x in tr.items() if len(x) == 3]
                flip = lambda t: int(t["resolving"]["any_rev"] and not t["irrelevant"]["any_rev"] and not t["irrelevant"]["any_conf"] and t["contradictory"]["any_conf"] and not t["contradictory"]["any_rev"])
                st = defaultdict(list)
                for t in triples:
                    st[t["story"]].append(t)
                fv = np.array([[sum(flip(t) for t in v), len(v)] for v in st.values()], float)
                fe = fv[:, 0].sum() / fv[:, 1].sum() if len(fv) else None
                if len(fv):
                    ix = RNG.integers(0, len(fv), size=(NB, len(fv))); bs = fv[ix].sum(1); bs = bs[:, 0] / bs[:, 1]; flo, fhi = np.percentile(bs, [2.5, 97.5])
                fl = f"{fe:.3f} [{flo:.3f}, {fhi:.3f}] (n={len(triples)})" if len(fv) else "n/a"
                L.append(f"| {m} | {s} | {scope} | {fmt(prop_ci(res_, lambda r: 1 - r['missed']))} | {fmt(prop_ci(irr, lambda r: 1 - r['collateral']))} | {fmt(prop_ci(con, lambda r: r['conf_ok']))} | {fmt(prop_ci(con, lambda r: r['any_rev']))} | {fl} |")

    # ---------------- C failure structure
    FEATS = ["n_events", "n_noops", "n_chars", "n_props", "n_sent", "ev_dist", "n_after", "shuffled", "heldout", "near", "past", "resolving", "contradictory", "dependent"]
    L += ["", "## C. What predicts failure? (exploratory; story-clustered bootstrap of logistic regression odds ratios per +1 SD / per indicator)", "",
          "Outcomes: collateral (any KEEP claim changed), missed (any gold REVISE claim not exactly revised; resolving items only), not-exact (delta EM failure). Features are standardised; `resolving/contradictory` are indicators vs irrelevant; features with zero variance are dropped. Collinearity between split indicators (shuffled/heldout/near) and size features is limited by design (each OOD axis is varied in one split).", ""]
    for m, d in R.items():
        for s in ("p2_explicit_revision",):
            rows = d.get(s)
            if not rows:
                continue
            for outcome, sel in (("collateral", rows), ("missed", [r for r in rows if r["cat"] == "resolving"]), ("not_exact", rows)):
                y = np.array([(1 - r["exact"]) if outcome == "not_exact" else r[outcome] for r in sel])
                if y.min() == y.max():
                    L.append(f"- {m} {s} {outcome}: constant outcome (no variance) — skipped.")
                    continue
                X = np.array([[r[f] for f in FEATS] for r in sel], float)
                keep = [i for i in range(len(FEATS)) if X[:, i].std() > 0 and not (outcome == "missed" and FEATS[i] in ("resolving", "contradictory"))]
                Xs = (X[:, keep] - X[:, keep].mean(0)) / X[:, keep].std(0)
                lr = LogisticRegression(C=1.0, max_iter=2000).fit(Xs, y)
                st = defaultdict(list)
                for i, r in enumerate(sel):
                    st[r["story"]].append(i)
                ids = list(st)
                coefs = []
                for _ in range(min(NB, 300)):
                    pick = RNG.integers(0, len(ids), len(ids))
                    ix = np.concatenate([st[ids[j]] for j in pick])
                    if y[ix].min() == y[ix].max():
                        continue
                    coefs.append(LogisticRegression(C=1.0, max_iter=2000).fit(Xs[ix], y[ix]).coef_[0])
                coefs = np.array(coefs)
                L += [f"**{m} · {s} · outcome={outcome}** (n={len(sel)}, base rate {y.mean():.3f})", "", "| feature | odds ratio | 95% CI |", "|---|---|---|"]
                for j, i in enumerate(keep):
                    lo, hi = np.exp(np.percentile(coefs[:, j], [2.5, 97.5]))
                    L.append(f"| {FEATS[i]} | {np.exp(lr.coef_[0][j]):.2f} | [{lo:.2f}, {hi:.2f}] |")
                L.append("")
    L += ["### Grouped failure rates (p2, all splits)", "", "| model | group | collateral rate | missed-revision rate (resolving) | not-exact rate |", "|---|---|---|---|---|"]
    for m, d in R.items():
        rows = d.get("p2_explicit_revision", [])
        for gname, sel in [("evidence family=" + f, [r for r in rows if r["family"] == f]) for f in sorted({r["family"] for r in rows})] + \
                          [(f"n_changed={k}", [r for r in rows if r["cat"] == "resolving" and r["n_changed"] == k]) for k in (1, 2, 3)] + \
                          [("dependent change", [r for r in rows if r["cat"] == "resolving" and r["dependent"]]), ("no dependent change", [r for r in rows if r["cat"] == "resolving" and not r["dependent"]]),
                           ("evidence in past", [r for r in rows if r["past"]]), ("evidence in future", [r for r in rows if not r["past"]])]:
            if len(sel) >= 15:
                res_ = [r for r in sel if r["cat"] == "resolving"]
                L.append(f"| {m} | {gname} | {fmt(prop_ci(sel, lambda r: r['collateral']))} | {fmt(prop_ci(res_, lambda r: r['missed'])) if len(res_) >= 15 else 'n/a'} | {fmt(prop_ci(sel, lambda r: 1 - r['exact']))} |")

    # ---------------- D OOD
    L += ["", "## D. Each held-out split vs test_id (p2 and p1; difference in rate, unpaired story-cluster bootstrap)", "", "| model | system | split | metric | test_id | split | diff (split - id) | 95% CI |", "|---|---|---|---|---|---|---|---|"]
    for m, d in R.items():
        for s in ("p1_zero_shot_delta", "p2_explicit_revision"):
            rows = d.get(s, [])
            base = [r for r in rows if r["split"] == "test_id"]
            for sp in TEST_SPLITS[1:]:
                oo = [r for r in rows if r["split"] == sp]
                if not oo or not base:
                    continue
                for name, f in (("collateral", lambda r: r["collateral"]), ("not-exact", lambda r: 1 - r["exact"])):
                    a, b = prop_ci(base, f), prop_ci(oo, f)
                    ids_a = sorted({r["story"] for r in base}); ids_b = sorted({r["story"] for r in oo})
                    va = np.array([[sum(f(r) for r in base if r["story"] == i), sum(r["story"] == i for r in base)] for i in ids_a], float)
                    vb = np.array([[sum(f(r) for r in oo if r["story"] == i), sum(r["story"] == i for r in oo)] for i in ids_b], float)
                    ba = va[RNG.integers(0, len(va), (NB, len(va)))].sum(1); bb = vb[RNG.integers(0, len(vb), (NB, len(vb)))].sum(1)
                    diff = bb[:, 0] / bb[:, 1] - ba[:, 0] / ba[:, 1]
                    lo, hi = np.percentile(diff, [2.5, 97.5])
                    L.append(f"| {m} | {s} | {sp} | {name} | {a[0]:.3f} | {b[0]:.3f} | {b[0] - a[0]:+.3f} | [{lo:+.3f}, {hi:+.3f}] |")

    # ---------------- E model comparison
    L += ["", "## E. Model comparison on shared items (McNemar exact test on per-item delta exactness; Holm-corrected within system)", "", "| system | model A | model B | A-only exact | B-only exact | both | neither | McNemar p | p (Holm) |", "|---|---|---|---|---|---|---|---|---|"]
    for s in DELTA:
        pairs, ps = [], {}
        for i, a in enumerate(MODELS):
            for b in MODELS[i + 1:]:
                ra, rb = {r["item"]: r["exact"] for r in R.get(a, {}).get(s, [])}, {r["item"]: r["exact"] for r in R.get(b, {}).get(s, [])}
                common = set(ra) & set(rb)
                if not common:
                    continue
                n10 = sum(ra[i_] and not rb[i_] for i_ in common); n01 = sum(rb[i_] and not ra[i_] for i_ in common)
                both = sum(ra[i_] and rb[i_] for i_ in common); nei = len(common) - n10 - n01 - both
                p = 1.0 if n10 + n01 == 0 else binomtest(n10, n10 + n01, 0.5).pvalue
                pairs.append((a, b, n10, n01, both, nei, p)); ps[f"{a}|{b}"] = p
        hp = stats.holm(ps) if ps else {}
        for a, b, n10, n01, both, nei, p in pairs:
            L.append(f"| {s} | {a} | {b} | {n10} | {n01} | {both} | {nei} | {p:.4g} | {hp[f'{a}|{b}']:.4g} |")
    open(os.path.join(OUT, "DEEP_ANALYSIS.md"), "w").write("\n".join(L) + "\n")
    json.dump(J, open(os.path.join(OUT, "deep_analysis.json"), "w"), indent=1)
    print("wrote DEEP_ANALYSIS.md")


if __name__ == "__main__":
    main()
