"""Run-completeness verification. Writes research/results/RUN_COMPLETENESS.md and exits 1 if anything is incomplete.

Expected keys are recomputed from the frozen subsample rule (run.pick_stories) — never from what happens to be on disk.
"""
from __future__ import annotations
import json, os, re, sys
from collections import Counter
from .io import TEST_SPLITS, load_task
from .run import DEFAULT_STORIES, RAW, STORIES_PER_SPLIT, K_SC, pick_stories
from .systems import common as C

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "results")
MODELS = ["qwen2.5:7b", "llama3:latest", "qwen3:8b", "mistral:7b"]
SYSTEMS = ["p1_zero_shot_delta", "p2_explicit_revision", "p3_regenerate", "p5_direct_qa", "p4_self_consistency"]
GOLD_TOKENS = ["RESOLVING", "IRRELEVANT", "CONTRADICTORY", "scope_bounded", "gold", "oracle", "probe_answer"]


def expected(system):
    splits = ["test_id"] if system == "p4_self_consistency" else TEST_SPLITS
    keys = set()
    for sp in splits:
        n = STORIES_PER_SPLIT.get(sp, DEFAULT_STORIES)
        for t in pick_stories(sp, load_task(sp), n):
            for k in (range(K_SC) if system == "p4_self_consistency" else [0]):
                keys.add(f"{sp}|{t['item_id']}|{k}")
    return keys


def main():
    L = ["# Run completeness report (generated by research/ssr_bench/verify_runs.py)", "",
         "| model | system | expected | present | missing | unexpected | duplicates | error records | empty content | invalid-claim rate | digests | COMPLETE |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    ok_all = True
    tasks_by_split = {sp: {t["item_id"]: t for t in load_task(sp)} for sp in TEST_SPLITS}
    for m in MODELS:
        for s in SYSTEMS:
            path = os.path.join(RAW, m.replace(":", "_"), f"{s}.jsonl")
            exp = expected(s)
            rows = [json.loads(l) for l in open(path)] if os.path.exists(path) else []
            keys = Counter(r["key"] for r in rows)
            missing, unexpected = exp - set(keys), set(keys) - exp
            dup = sum(v > 1 for v in keys.values())
            err = sum(bool(r["error"]) for r in rows)
            empty = sum(not r["content"] for r in rows)
            inv = tot = 0
            for r in rows:
                if s != "p5_direct_qa" and r["content"]:
                    _, bad = C.parse_delta(s, r["content"], tasks_by_split[r["split"]][r["item_id"]])
                    inv += bad; tot += 10
            dig = len({r["model_digest"] for r in rows})
            complete = bool(rows) and not missing and not unexpected and not dup and not err and dig == 1
            ok_all &= complete
            L.append(f"| {m} | {s} | {len(exp)} | {len(rows)} | {len(missing)} | {len(unexpected)} | {dup} | {err} | {empty} | {inv / tot:.4f} | {dig} | {'YES' if complete else '**NO**'} |" if tot else
                     f"| {m} | {s} | {len(exp)} | {len(rows)} | {len(missing)} | {len(unexpected)} | {dup} | {err} | {empty} | n/a | {dig} | {'YES' if complete else '**NO**'} |")
    # prompts contain no gold metadata: re-render every prompt template for one item per split and scan
    leaks = []
    for sp in TEST_SPLITS:
        t = next(iter(tasks_by_split[sp].values()))
        for s in ("p1_zero_shot_delta", "p2_explicit_revision", "p3_regenerate", "p5_direct_qa"):
            p = C.build_prompt(s, t)
            for tok in GOLD_TOKENS:
                if re.search(tok, p, re.I) and tok not in ("gold",):
                    leaks.append((sp, s, tok))
    L += ["", f"Prompt scan for gold/category tokens {GOLD_TOKENS}: {'none found' if not leaks else leaks}",
          "Evaluator inputs: `evaluate.py` / `metrics.item_counts` read task claims (id, attr, entity, slot) and gold labels/meta only; model code under `systems/` is import-checked by tests.", "",
          f"**OVERALL: {'ALL RUNS COMPLETE' if ok_all and not leaks else 'INCOMPLETE OR INVALID — do not treat as complete'}**"]
    open(os.path.join(OUT, "RUN_COMPLETENESS.md"), "w").write("\n".join(L) + "\n")
    print("\n".join(L))
    sys.exit(0 if ok_all and not leaks else 1)


if __name__ == "__main__":
    main()
