import asyncio
import os
import time

from backend.ingestion.parsers import ScreenplayParser
from backend.ingestion.models import NarrativeUnit
from backend.clickhouse.client import ClickHouseClient
from backend.candidate_detection.detector import CandidateDetector
from backend.llm.base import LLMProvider
from backend.llm.client import GeminiProvider
from backend.llm.ollama import OllamaProvider
from backend.pipeline.state_extraction import extract_state_events, write_state_events


def _default_provider() -> LLMProvider:
    """MODEL_PROVIDER=ollama (default) runs free/local for heavy passes;
    MODEL_PROVIDER=gemini switches to the paid API tier."""
    if os.environ.get("MODEL_PROVIDER", "ollama") == "gemini":
        return GeminiProvider()
    return OllamaProvider()


async def run_pipeline(
    units: list[NarrativeUnit],
    story_universe_id: str,
    client: ClickHouseClient,
    llm: LLMProvider | None = None,
) -> None:
    """Shared orchestration: insert units, extract state events per unit via
    the LLM, write them, then run candidate detection. Used by the screenplay
    demo below and by the Reverend Insanity pipeline validation."""

    client.insert_narrative_units(units)
    print(f"✓ Inserted {len(units)} narrative units into ClickHouse Story State DB")

    llm = llm or _default_provider()
    print(f"  Using {llm.tier} provider: {llm.model}", flush=True)
    total_events = 0
    start = time.monotonic()
    for i, unit in enumerate(units, 1):
        unit_start = time.monotonic()
        events = await extract_state_events(unit, story_universe_id, llm)
        await write_state_events(events, client)
        total_events += len(events)
        elapsed = time.monotonic() - start
        avg = elapsed / i
        remaining = avg * (len(units) - i)
        print(
            f"  [{i}/{len(units)}] {unit.unit_id}: {len(events)} events "
            f"({time.monotonic() - unit_start:.1f}s, ~{remaining / 60:.0f}m left)",
            flush=True,
        )
    print(f"✓ Extracted and wrote {total_events} state events across {len(units)} units")

    detector = CandidateDetector(client)
    conflicts = detector.detect_conflicts(story_universe_id)
    print(f"✓ Detected {len(conflicts)} candidate conflicts using SQL Window Functions")


def run_demo():
    print("Starting StoryTrace Demo Pipeline...")

    # 1. Parse PDF - demo/screenplay.pdf is an input fixture (generated by
    # scripts/generate_demo_pdf.py) consumed by the ScreenplayParser adapter.
    parser = ScreenplayParser("demo_script")
    pdf_path = "demo/screenplay.pdf"
    if not os.path.exists(pdf_path):
        print(f"Error: {pdf_path} not found. Run scripts/generate_demo_pdf.py first.")
        return

    units = parser.parse(pdf_path)
    print(f"✓ Parsed {len(units)} narrative units from {pdf_path}")

    # 2. Connect to ClickHouse (Requires docker-compose up)
    try:
        client = ClickHouseClient()
    except Exception as e:
        print(f"⚠ Could not connect to ClickHouse. Is docker-compose running? ({e})")
        print("Skipping database steps for demo.")
        return

    # 3. Insert units, extract state events, detect candidates
    asyncio.run(run_pipeline(units, "demo_script", client))

    # 4. Investigation Agent (invoked separately per candidate, not part of this script)
    print("\n--- Pipeline Execution Complete ---")
    print("Start the FastAPI server and Next.js UI to explore the Continuity Autopsy.")


if __name__ == "__main__":
    run_demo()
